### ISSUE TITLE
Initial prototype feedback from Hazel

### ISSUE THREAD

**Issue by Oliversw** [GSG-G7/far-nearer#10]
1. Can we call the project: "Who owns our neighbourhood?" rather than Far Nearer? I want to distinguish this project from my earlier work on Far Nearer.

2. We need to narrow the scope of the investigation to a couple of neighbourhoods in the UK, as at the moment anyone can put in data for anywhere. So perhaps the landing page could be a map of the UK and you can click through to select either Morecambe or Hastings, to start with, as these are two towns I am working with. Or perhaps it should just have two buttons to select either "Morecambe" or "Hastings".

3. On the next page, the user should be able to see a map of the neighbourhood (see screengrabs) and through a floating box, add information about the empty building, BEFORE they go to the name, email address page. 

4. *I have attached two screengrabs of Morecambe and Hastings neighbourhoods to use as a background if you want. Or maybe the app could open on one of these maps, like the Rent Check app, so you can immediately see which neighbourhood the investigation is taking place in.*

5. *I have been thinking more about the potential downsides to making this data publicly available – in case it compromises the security of any of the empty buildings for example. When we have some of this data, perhaps we could have blobs to show the streets the empty buildings are on (like Rent Check), then if you click on a blob to expand the locations of the buildings, you get asked to register, and only people with a local postcode are able to register, everyone else can request access (from me, I guess).*
 

6. Please can you take my picture off the "about us"? I will send you some text to change it to. I will also send some text for the "about this project" section.

<img width="1082" alt="Morecambe" src="https://user-images.githubusercontent.com/9094166/67272364-4b87ea80-f4b4-11e9-8a7a-5984ff429531.png">
<img width="721" alt="Hastings" src="https://user-images.githubusercontent.com/9094166/67272366-4c208100-f4b4-11e9-8254-1eddef9368a9.png">

**Comment by Oliversw** [comment]
Hi @hazelsheffield! Could you please give us some clarification about this point:
> 4. I have attached two screengrabs of Morecambe and Hastings neighbourhoods to use as a background if you want. Or maybe the app could open on one of these maps, like the Rent Check app, so you can immediately see which neighbourhood the investigation is taking place in.

Where would you imagine using these screengrabs as a background? Also when would you imagine opening to one of thesse maps? After selecting a town?

**Comment by Oliversw** [comment]
Also regarding the following point @hazelsheffield:
> I have been thinking more about the potential downsides to making this data publicly available – in case it compromises the security of any of the empty buildings for example. When we have some of this data, perhaps we could have blobs to show the streets the empty buildings are on (like Rent Check), then if you click on a blob to expand the locations of the buildings, you get asked to register, and only people with a local postcode are able to register, everyone else can request access (from me, I guess).

I think I understand what you are saying, but that might be a bit too technically complex for the moment. The Rent Check blobs are controlled by how zoomed in or out that the user is on the map (which we might be able to implement if we finish the rest of the functionality), so controlling that by whether the user is logged in or not is a lot more complicated.
How would you imagine people with a local postcode registering? In the workshop we had spoken more about having a single login that you would be sharing with people so that they could access the information.

Thanks for any and all clarification!! 😄

**Comment by hazelsheffield** [comment]
Hi there,

I think it would be a good idea to open on the relevant map after you select the town.

I provided the screen grabs and links only in case they are useful to you to use on these pages, rather than the stock images you have. 

Does that help?

**Comment by Oliversw** [comment]
That's great, thanks @hazelsheffield! Does that work for you @ahmedisam99?

Also regarding the new name that is totally fine. Do you have any kind of logo that you might like them to use instead of the Far Nearer logo?

**Comment by Mohammed-Q96** [comment]
We are currently working on it

**Comment by Mohammed-Q96** [comment]
We are currently working on it @Oliversw
