### ISSUE TITLE
Google sheet for private details (.env file, logins)

### ISSUE THREAD

**Issue by Oliversw** [GSG-G7/far-nearer#4]
[Document available here](https://docs.google.com/spreadsheets/d/1e3u00z4Vp6f-NAOcob8F4cUtS1yn08HytlCHYW5Jlag/edit?usp=sharing)
NOTE: I will need your emails to add you as collaborators to the document so you can see it! Please ask Ahmed to send it to me in the Slack.

This is for keeping .env details (heroku, apis, etc), as well as any logins that we might have. We are keeping it in a private google sheet so that it is not exposed publicly on Github.

**Comment by ahmedisam99** [comment]
**Ahmed Abdellatif:** ahmedisam9922@gmail.com
**Fadi Alamassi:** alamassifadi@gmail.com
**maiubeid:** ubead95@gmail.com

**Comment by Oliversw** [comment]
Thanks @ahmedisam99!! I have shared this document as well as a google calendar with you all! Remember that this is a public Github though, so you might want to delete that comment if you don't want your emails out there! :)

**Comment by ahmedisam99** [comment]
@Oliversw 
Which will be preferred regarding `airtable` account:
- Create an account using the traditional way (first name, last name, ...etc). Using Hazel's email but of course, with a different password which will be shared among us and Hazel will be free to change it afterward.
- Signup using Google by creating a new Google account.
- Creating a new account for the development and afterward, hazel can create hers and update the environment variables.

**Comment by Oliversw** [comment]
@ahmedisam99 What I have always done in the past is to create an Airtable base with my own account. When it comes to the handover it is not very hard to transfer ownership to Hazel by sharing the workspace and changing permissions.
Having ownership during development hopefully prevents problems with permissions and access, so I think that might be best!
