### ISSUE TITLE
fix bug with errorHandle middleware

### ISSUE THREAD

**Issue by ahmedisam99** [GSG-G7/far-nearer#50]
- The server always sends a status code of 200 from `errorHandle` middleware
- In addition, a wrong status code is sent from the server in the cases when the server fails to process something `(internal server error)`

**To Reproduce _(locally using development env)_**
1. run the server 
`$ npm run dev`
2. turn off the wifi (so the server cannot reach airtable)
3. head to `localhost:5000/api/v1/empty-buildings`
4. See the error, as the server responds with a status code of `200 ok` and a body with only the error (and without the right status code)

**Expected behavior**
The server `errorHandle` middleware must always send the right status code which in our case there are two status codes sent by this middleware:
- 413
- 500

**Screenshots**
![Screenshot from 2019-10-29 21-30-19](https://user-images.githubusercontent.com/35656148/67802541-00fa0580-fa94-11e9-9556-ba9d7211c76a.png)

**Comment by MaiUbeid** [comment]
This is what appeared on my browser !!
Is I need to handle other errors? and ensure of 200 or 500 status code?
 
![Screenshot from 2019-10-29 22-42-11](https://user-images.githubusercontent.com/20427049/67807424-6f8f9100-fa9d-11e9-9c65-371b3c1fe544.png)

**Comment by MaiUbeid** [comment]
Did you mean that I need to handle other errors? and ensure of 200 or 500 status code?
@ahmedisam99

**Comment by MaiUbeid** [comment]
This happens because statusCode is undefined in the following code:
```
const { statusCode } = err; 
```
The error that comes from airtable is:
```
Error: getaddrinfo ENOTFOUND api.airtable.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.airtable.com'
}
```
So I work to have the statusCode from airtable error 
@ahmedisam99

**Comment by ahmedisam99** [comment]
@MaiUbeid 
I think the code works just fine, the problem only happens when the error is not generated bu `airtable` so there will not be a `statusCode` in it, so my suggestion is only to give `statusCode` a default value
```js
const { statusCode = 500 } = err
```

**Comment by MaiUbeid** [comment]
Yes, in 505 error there are no statusCode 
If the error is 413, statusCode will be sent bu airtable?!

**Comment by MaiUbeid** [comment]
@ahmedisam99 
Also if we add default status code to be 500, it doesn't appear in the network, as follow:
![Uploading Screenshot from 2019-10-29 23-33-42.png…]()

**Comment by ahmedisam99** [comment]
this bug is a result of the following code:
```js
res.send({ statusCode, error: message });
```
Calling `res.send` sets the status code to be `200` by default, so what you need to do is :
```js
res.status(statusCode).send({ statusCode, error: message });
```
