### ISSUE TITLE
Page list with acceptance criteria

### ISSUE THREAD

**Issue by Oliversw** [GSG-G7/far-nearer#6]
NOTE: This will be updated as we get more information.

There are not a lot of different pages at this point, but there is a lot of complexity with the map/database/client backend/login etc.

- [ ] Landing/map(?) page
   - [ ] small intro/tagline about the project
   - [ ] link to about page
   - [ ] link to report an empty building
   - [ ] link to log in to see the full view
   - [ ] map or list view of reportedly empty buildings (depending on choices for final tech stack)
      - [ ] record for each reportedly empty building shows data when logged in
   - [ ] Stretch: Non logged in user can see basic information about reportedly empty buildings
- [ ] About page
   - [ ] Copy about the project and the app
   - [ ] Button to sign up to mailing list (stretch)
- [ ] User input page/popup (report an empty building)
   - [ ] What is the address of the empty building? (text input? Depends what might work best with the map if we use it)
   - [ ] What was it used for: residential, retail, office, community building, other (specify)? (Maybe dropdown?)
   - [ ] Who owns it?  (text form and tick box for don't know)
   - [ ] Are they local? (yes, no, don't know check boxes)
   - [ ] How long has it been empty for? (text input and check box for don't know)
   - [ ] What would you like to see it used for? (text input)
   - [ ] Any other information? (text input)
- [ ] Login page/popup
   - [ ] input for master password
   - [ ] submit button
- [ ] Stretch: Client backend (currently Airtable database)
   - [ ] client can mark a building as confirmed empty or occupied
   - [x] client can edit records (checked because Airtable handles that automatically)

**Comment by Oliversw** [comment]
Please let me know if I have forgotten anything or if you think that something should be changed!

**Comment by ahmedisam99** [comment]
Regarding:
 [ ] small intro/tagline about the project
 [ ] link to about page

These two seem to be the same (correct me if I'm wrong).
Won't they describe the same thing (_i.e._ have the same content)?

And for the login page, now that we are using airtable login will be done using the supplied username and password instead of the master password

**Comment by Oliversw** [comment]
> These two seem to be the same (correct me if I'm wrong).
Won't they describe the same thing? (i.e. have the same content)

They are definitely describing the same kind of thing, but might be slightly different in their content. The idea is more that there will be some kind of (brief) explanation about the project even if people don't go to the about page.

> And for the login page, now that we are using airtable, login will be done using the supplied username and password instead of the master password.
I believe that the login page is for people who would are involved with local communities and would like to contribute to the project. The login is so that they can have access to the extra information, whereas the Airtable is purely for Hazel, at least in my understanding. We can talk about it in our meeting in the morning though!

**Comment by Oliversw** [comment]
Closing to replace with new criteria after user testing
