### ISSUE TITLE
Consider using 'Squash and Merge' when merging pull requests

### ISSUE THREAD

**Issue by poiru** [GSG-G7/far-nearer#68]
When merging pull requests, the default is "Merge pull request". This merges all individual commits from the pull request branch into `master`. One of the downsides of this approach is that the Git commit history becomes non-linear and very difficult to understand.

For example, right now this repo has commits like:

* resolve conflicts 
* Merge branch 'master' of https://github.com/GSG-G7/far-nearer into ...

I propose using "Squash and merge" instead. This combines all the individual commits in the pull request branch to just one commit. It makes it much easier review the history.

You can read more here:
* https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges
* https://stackoverflow.com/questions/20348629/what-are-advantages-of-keeping-linear-history-in-git

You can also disable "Merge pull request" in the repo settings if you decide to go with the proposal.

cc @ahmedisam99

**Comment by ahmedisam99** [comment]
Great @poiru :+1:
